-- CreateEnum
CREATE TYPE "ActivityActionType" AS ENUM ('ASSIGNEE_ADDED', 'ASSIGNEE_REMOVED', 'FILE_ADDED', 'FILE_REMOVED', 'LINK_ADDED', 'LINK_REMOVED', 'DUE_DATE_CHANGED', 'PROGRESS_CHANGED', 'SUBTASK_ADDED', 'SUBTASK_REMOVED', 'STATUS_CHANGED', 'PRIORITY_CHANGED', 'COMMENT_ADDED', 'PROJECT_CREATED', 'PROJECT_UPDATED', 'TASK_CREATED', 'TASK_COMPLETED', 'GENERAL');

-- AlterTable
ALTER TABLE "activities" ADD COLUMN     "actionType" "ActivityActionType" NOT NULL DEFAULT 'GENERAL';
